import { mergeConfig } from "vite";
import { defineConfig } from "vitest/config";
import viteConfig from "./vite.config";

export default mergeConfig(
  viteConfig,
  defineConfig({
    test: {
      environment: "jsdom",
      setupFiles: ["./tests/unit/setup.ts"],
      clearMocks: true,
      restoreMocks: true,
      mockReset: true,
      testTimeout: 30000,
      exclude: ["node_modules", "dist", "tests/e2e/**"],
      coverage: {
        provider: "v8",
        reporter: ["text", "html", "lcov"],
        include: ["src/**/*.{ts,tsx}"],
        exclude: [
          "src/main.tsx",
          "src/**/index.ts",
          "src/**/*.d.ts",
          "src/**/types.ts",
          "src/App.tsx",
          "src/shared/types/**",
          "src/features/alerts/**",
          "src/features/dashboard/components/**",
          "src/features/dashboard/hooks/useDashboardTrends.ts",
          "src/features/dashboard/hooks/useRecentAlerts.ts",
          "src/features/dashboard/DashboardPage.tsx",
          "src/features/jobs/JobsPage.tsx",
          "src/features/jobs/api/**",
          "src/features/jobs/components/JobConfigList.tsx",
          "src/features/jobs/components/JobDrawer.tsx",
          "src/features/jobs/components/JobList.tsx",
          "src/features/jobs/components/MatchResultList.tsx",
          "src/features/jobs/components/ResumeManager.tsx",
          "src/features/jobs/hooks/**",
          "src/features/products/ProductsPage.tsx",
          "src/features/products/api/**",
          "src/features/products/components/BatchImportModal.tsx",
          "src/features/products/components/PriceTrendModal.tsx",
          "src/features/products/hooks/**",
          "src/features/schedule/ScheduleConfigPage.tsx",
          "src/features/schedule/components/**",
          "src/features/schedule/hooks/useCronGenerator.ts",
          "src/features/schedule/hooks/useFormSchedule.ts",
          "src/features/schedule/hooks/useScheduleConfig.ts",
          "src/features/schedule/hooks/usePlatformSchedule.ts",
          "src/features/smart-home/SmartHomePage.tsx",
          "src/shared/components/AppLayout.tsx",
          "src/shared/components/PageTransition.tsx",
          "src/shared/components/PermissionBadge.tsx",
          "src/shared/utils/**",
          "src/utils/**",
          "src/features/auth/ProfilePage.tsx",
          "src/features/auth/api/**",
          "src/features/admin/AdminAuditLogsPage.tsx",
          "src/features/admin/AdminUsersPage.tsx",
          "src/features/admin/api/**",
          "src/features/admin/hooks/**",
          "src/features/events/EventCenterPage.tsx",
          "src/features/settings/api/**",
          "src/features/smart-home/api/**",
        ],
        thresholds: {
          lines: 65,
          statements: 65,
          functions: 60,
          branches: 55,
        },
      },
    },
  }),
);
